// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfgrywkbmhfpvtpafwlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZ3J5d2tibWhmcHZ0cGFmd2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTk4OTgsImV4cCI6MjA2NjE3NTg5OH0.ASKKpI8oyT0ZFp7oeThrsxsWNCVGJpT5GsV1OyulnHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);